databases:
  - name: Image_Geneate_ai
    plan: free
    databaseName: Image_Geneate_ai
    user: Image_Geneate_ai_user

services:
  - type: web
    plan: free
    name: Image_Geneate_ai
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Image_generator.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://image_geneate_ai_user:tX6HFxiludmThf4L6BUrlSNAtWFGGob9@dpg-cv2kk10fnakc738bib8g-a/image_geneate_ai
        fromDatabase:
          name: Image_Geneate_ai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4